#!/usr/bin/env python
from hippocampus_common.node import Node
import matplotlib.pyplot as plt


class Plotter(Node):
    def __init__(self, name):
        super(Plotter, self).__init__(name=name)
        path = self.get_param("~path")

        if path is None:
            exit(1)

        x, y, z = self.get_xyz_from_path(path)

        plt.plot(x, y)
        plt.show()

    def get_xyz_from_path(self, path):
        x = []
        y = []
        z = []
        for point in path:
            x.append(point["x"])
            y.append(point["y"])
            z.append(point["z"])
        return x, y, z


def main():
    Plotter("path_plotter")


if __name__ == "__main__":
    main()
