start_position: {x: 0.5, y: 1.0, z: -0.5}
loop: true
path:
- {x: 0.9, y: 1.0, z: -0.5}
- {x: 1.0, y: 1.0, z: -0.5}
- {x: 1.1, y: 1.0, z: -0.5}
- {x: 1.2, y: 1.0, z: -0.5}
- {x: 1.3, y: 1.0, z: -0.5}
- {x: 1.4, y: 1.0, z: -0.5}