#! /usr/bin/env python
from pydoc import describe
import gantry_control
import sys
import argparse


def main(port, baud, timeout):
    motor = gantry_control.create(port, baud, timeout)
    print(type(motor))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--port', default='/dev/ttyUSB0')
    parser.add_argument('--baud', default=19200)
    parser.add_argument('--timeout', default=0.5)
    args = parser.parse_args()
    main(args.port, args.baud, args.timeout)
